<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gallery_model extends CI_Model
{

    public $table = 'gallery';
    public $id = 'gallery_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('gallery_id', $q);
	$this->db->or_like('gallery_date', $q);
	$this->db->or_like('gallery_title', $q);
	$this->db->or_like('gallery_image', $q);
	$this->db->or_like('gallery_status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('gallery_id', $q);
	$this->db->or_like('gallery_date', $q);
	$this->db->or_like('gallery_title', $q);
	$this->db->or_like('gallery_image', $q);
	$this->db->or_like('gallery_status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_next_gallery_id() {
         $query = $this->db->query("SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_NAME ='gallery'");
         if ($query->num_rows() == 1) {
            return $query->row('AUTO_INCREMENT');
          } else {
            return 0;
          }  
    }

}

/* End of file Gallery_model.php */
/* Location: ./application/models/Gallery_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-23 04:46:34 */
/* http://harviacode.com */