<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class General_model extends CI_Model
{

    public $table = 'general';
    public $id = 'g_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_id_array($id) {
        $this->db->where($this->id, $id);
        $query = $this->db->get($this->table);
        return $query->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('g_id', $q);
	
	$this->db->or_like('g_home_title', $q);
	$this->db->or_like('g_home_desc', $q);
	$this->db->or_like('g_contact_info', $q);
	$this->db->or_like('g_address', $q);
	$this->db->or_like('g_email', $q);
	$this->db->or_like('g_phone', $q);
	$this->db->or_like('g_facebook', $q);
	$this->db->or_like('g_bankname', $q);
    $this->db->or_like('g_bankaccount', $q);
	//$this->db->or_like('g_status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('g_id', $q);
	
	$this->db->or_like('g_home_title', $q);
	$this->db->or_like('g_home_desc', $q);
	$this->db->or_like('g_contact_info', $q);
	$this->db->or_like('g_address', $q);
	$this->db->or_like('g_email', $q);
	$this->db->or_like('g_phone', $q);
	$this->db->or_like('g_facebook', $q);
	$this->db->or_like('g_bankname', $q);
     $this->db->or_like('g_bankaccount', $q);
	//$this->db->or_like('g_status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }


    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    
         //Whatsapp Call Me Bot
    // get data by id
    function get_wa_id($wid)
    {
        $this->db->where('wa_id', $wid);
        return $this->db->get('wa_callmebot')->row();
    }


    

}

/* End of file General_model.php */
/* Location: ./application/models/General_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-03 18:03:55 */
/* http://harviacode.com */