<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class News_model extends CI_Model
{

    public $table = 'news';
    public $id = 'news_id';
    public $status = 'news_status';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->status, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_all_active()
    {
        $this->db->where($this->status, "Aktif");
        $this->db->order_by('news_timestamp', $this->order);
        return $this->db->get($this->table)->result();
    }
/*
    function get_all_active() {
        //$this->db->select('userId,name');
        //$this->db->from('tbl_users');
        //$this->db->like('name', $name);
        //return $this->db->get()->result();

        $this->db->select('news_headline'); 
        $this->db->from('news');
        $this->db->where('news_status', 'Aktif');
        $this->db->order_by('news_status','ASC');
        $query = $this->db->get();
        return $query->result();
    }*/

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('news_id', $q);
	$this->db->or_like('news_headline', $q);
	$this->db->or_like('news_story', $q);
	$this->db->or_like('news_editor', $q);
	$this->db->or_like('news_email', $q);
	$this->db->or_like('news_timestamp', $q);
	$this->db->or_like('news_status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('news_id', $q);
	$this->db->or_like('news_headline', $q);
	$this->db->or_like('news_story', $q);
	$this->db->or_like('news_editor', $q);
	$this->db->or_like('news_email', $q);
	$this->db->or_like('news_timestamp', $q);
	$this->db->or_like('news_status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file News_model.php */
/* Location: ./application/models/News_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-28 09:16:45 */
/* http://harviacode.com */