<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Toyyibpay_model extends CI_Model
{

    public $table = 'payment_gateway';
    public $id = 'pg_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('pg_id', $q);
	$this->db->or_like('pg_url', $q);
	$this->db->or_like('pg_secretkey', $q);
	$this->db->or_like('pg_catcode', $q);
	$this->db->or_like('pg_billname', $q);
	$this->db->or_like('pg_returnurl', $q);
	$this->db->or_like('pg_callbackurl', $q);
	$this->db->or_like('pg_createbill', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('pg_id', $q);
	$this->db->or_like('pg_url', $q);
	$this->db->or_like('pg_secretkey', $q);
	$this->db->or_like('pg_catcode', $q);
	$this->db->or_like('pg_billname', $q);
	$this->db->or_like('pg_returnurl', $q);
	$this->db->or_like('pg_callbackurl', $q);
	$this->db->or_like('pg_createbill', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Toyyibpay_model.php */
/* Location: ./application/models/Toyyibpay_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-08-11 23:32:32 */
/* http://harviacode.com */