<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Whatsapp_model extends CI_Model
{

    public $table = 'whatsapp_message';
    public $table_bot = 'wa_callmebot';
    public $id = 'wm_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {

        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('wm_id', $q);
	$this->db->or_like('userid', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('messageid', $q);
	$this->db->or_like('message', $q);
	$this->db->or_like('createDtm', $q);
	$this->db->or_like('createdBy', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('wm_id', $q);
	$this->db->or_like('userid', $q);
	$this->db->or_like('phone', $q);
	$this->db->or_like('messageid', $q);
	$this->db->or_like('message', $q);
	$this->db->or_like('createDtm', $q);
	$this->db->or_like('createdBy', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // get data with limit and search
    /*
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->select('Wam.wm_id, Wam.userid, Wam.phone, Wam.messageid, Wam.message, Wam.createDtm, Wam.createdBy, Usr.userid, Usr.name');
        $this->db->from('whatsapp_message as Wam');
        $this->db->join('tbl_users as Usr', 'Usr.userId = Wam.userid','left');

    $this->db->order_by($this->id, $this->order);
    $this->db->like('Wam.wm_id', $q);
    $this->db->or_like('Usr.userid', $q);
    $this->db->or_like('Usr.name', $q);
    $this->db->or_like('Wam.phone', $q);
    $this->db->or_like('Wam.messageid', $q);
    $this->db->or_like('Wam.message', $q);
    $this->db->or_like('Wam.createDtm', $q);
    $this->db->or_like('Wam.createdBy', $q);
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    */
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    //Whatsapp Call Me Bot
    // get data by id
    function get_wa_id($wid)
    {
        $this->db->where('wa_id', $wid);
        return $this->db->get('wa_callmebot')->row();
    }

    //Whatsapp Wamessengger
    // get data by id
    function get_whatsapp_id($wid)
    {
        $this->db->where('w_id', $wid);
        return $this->db->get('whatsapp_host')->row();
    }

    // insert data
    function insert_whatsapp($data)
    {
        $this->db->insert('whatsapp_message', $data);
    }

    function get_phone($waid,$column)
    {
        $this->db->select($column);
        $this->db->from("wa_callmebot");
        $this->db->where("wa_id", $waid);
        return $this->db->get()->row()->$column;
    }

    // update data
    function update_phone($waid, $data)
    {
        $this->db->where("wa_id", $waid);
        $this->db->update($this->table_bot, $data);
    }

}

/* End of file Whatsapp_model.php */
/* Location: ./application/models/Whatsapp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-03-27 00:45:13 */
/* http://harviacode.com */